[server]
headless = true
enableCORS = false
port = 8501
runOnSave = true

[theme]
base = "light"
primaryColor = #1f77b4
backgroundColor = '"#ff00ff"'
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false
